### ISSUE TITLE
Auto initialize tracing of requests and database access

### ISSUE THREAD

**Issue by carlo-quinonez** [Dynatrace/OneAgent-SDK-for-NodeJs#14]
It's not clear how to use the agent to trace REST requests. The [example for tracing outgoing requests](https://github.com/Dynatrace/OneAgent-SDK-for-NodeJs/blob/master/samples/RemoteCall/OutgoingRemoteCallSample.js) doesn't even make an actual request.

It would ideal if the agent included an open to setup autocollection, like the MS AppInsights agent does [this](https://github.com/microsoft/ApplicationInsights-JS#setting-up-autocollection). I realize that autocollection doesn't cover any advanced use-cases, but it would make it a lot easier to get started with the agent.

**Comment by Flarna** [comment]
HTTP requests are captured by OneAgent without the need to use SDK. 

The SDK is only intended to manually add support for protocols not supported by OneAgent out of the box - like the IPC in the sample.

> The [example for tracing outgoing requests](https://github.com/Dynatrace/OneAgent-SDK-for-NodeJs/blob/master/samples/RemoteCall/OutgoingRemoteCallSample.js) doesn't even make an actual request.

Actually it does at here https://github.com/Dynatrace/OneAgent-SDK-for-NodeJs/blob/7c3bcfec43fe1b0ab69ff97477c229e0df3e0f57/samples/RemoteCall/OutgoingRemoteCallSample.js#L63

**Comment by carlo-quinonez** [comment]
Any examples of integrating OneAgent into a Node project? I saw OneAgent automatically instruments requests, databases, etc. I'd like to see how to set contexts for correlating. I read the docs on [contexts](https://github.com/Dynatrace/OneAgent-SDK-for-NodeJs#pass-context) and had a couple of questions.
1. Does the OneAgent automatically wrap callbacks?
2. If I have to manually wrap callbacks, how do I create the context? Is that what the `.createInstance()` function does?
3. Will context be preserved when using async/await syntax instead of callbacks?

Regarding the sample file I mentioned... If you follow that call all the way through the code, it's not obvious what happens because it's complicated (forking a process to handle sending request?) and confusing (the _outgoing_ call handler uses the _incoming_ call handler to send requests?). Anyways, it could definitely be improved as documentation that helps new users understand what's going on.

**Comment by Flarna** [comment]
It seems your questions are more related to OneAgent itself and not the OneAgent-SDK-for-NodeJs module (this module). The OneAgent-SDK-for-NodeJs is used to manually add transactions not monitored on default by OneAgent.

This module here requires an installed OneAgent otherwise it does nothing- it's an optional addition to OneAgent.

OneAgent automatically instruments supported libraries and wraps callbacks for supported technologies. For more details regarding OneAgent I recommend to get in contact with dynatrace sales team and/or start a free trial.

It's quite likely that you don't need the OneAgent-SDK-for-NodeJs at all. Only few customers are actually using it as in most cases its not needed at all.


> forking a process to handle sending request?

It's not forking to send a request. It's forking to have a full running sample showing some sort of IPC between processes.
The sample contains sender and receiver (two processes). One process sends a request represented as an `OutgoingRemoteCall` service and other process receives this message represented as an `IncomingRemoteCall` service.

**Comment by Flarna** [comment]
closing, feel free to reopen/create a new issue in case of further questions.
