### ISSUE TITLE
Trace context lost for asynchronous requests

### ISSUE THREAD

**Issue by doudus** [Dynatrace/OneAgent-SDK-for-NodeJs#22]
For asynchronous apps that near-immediately respond to requests with a 202 - Accepted, the trace context is lost immediately after the .sendStatus(202) call. 

In Dynatrace purepath/diagnostic trace view, we can see child entries like database calls and service-to-service calls that occur after the 202 response. It would be ideal if the SDK could do the same and persist trace context through the end of the transaction. As it stands now, we cannot create request attributes after the initial 202 response.

**Comment by Flarna** [comment]
It's not really a context loss here. This is a limitation of how request attributes are attached to a trace.

As of now request attributes can be only attached to an open request. Once you send the 202 response the web request trace entry is ended and as a result the request attribute can't be attached anymore.
In contrast to request attributes other children like DB, HTTP or messaging requests (even when done via SDK) create a new linked entry in the trace but that's currently not supported for request attributes.

However, request attributes can be attached to this children and they are propagated up to the web request. But again they have to be added when the request is still ongoing.

Here is a small sample to illustrate this:
```typescript
import * as http from "http";
import { createInstance } from "@dynatrace/oneagent-sdk";

const sdk = createInstance();
sdk.setLoggingCallbacks({
  error(msg) { console.log("sdk error:", msg) },
  warning(msg) { console.log("sdk warn:", msg) }
});

http.createServer((req, res) => {
  sdk.addCustomRequestAttribute("onRequest", "works");
  res.statusCode = 202;
  res.end();
  sdk.addCustomRequestAttribute("afterEnd sync in handler", "works");

  setImmediate(() => {
    sdk.addCustomRequestAttribute("afterEnd async", "works not");

    http.get("http://example.org", (cltRsp) => {
      cltRsp.resume();
      sdk.addCustomRequestAttribute("inCltCb", "works again as in a sync callback");
    });
  });
}).listen(8100);
```

The SDK log `attribute <afterEnd async> not added because no active trace context found` is a bit misleading here. A better wording would be probably `attribute <afterEnd async> not added because no transaction is active`.

fyi @z1c0

**Comment by Flarna** [comment]
I will close this issue. Feel free to reopen in case you have more questions regarding this.
